---
##############################################################################
# setup locales
##############################################################################
# fix issues with locales, use locale_gen module
- name: Ensure locales exists.
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ langs }}"
  notify:
    - regenerate locales

- name: update packages
  apt: update_cache=yes

##############################################################################
# upgrade system
##############################################################################
# do-release-upgrade with Ansible
# See:
# https://www.jeffgeerling.com/blog/2017/
#     ansible-playbook-upgrade-all-ubuntu-1204-lts-hosts-1404-or-1604
- name: Update packages.
  apt: update_cache=yes

- name: Remove the EOL message of the day if one exists.
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/update-motd.d/99-esm
    - /run/motd.dynamic

- name: Upgrade all packages to the latest version
  apt: update_cache=yes upgrade=full

- name: upgrade all packages to the latest version
  apt: update_cache=yes upgrade=full

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

##############################################################################
# install basic packages
##############################################################################
# install a list of packages with Ansible
# see:
#   https://www.randomhacks.co.uk/
#     how-to-install-a-list-of-packages-with-ansible/
- name: Install packages
  apt:
    name: "{{ basic_packages }}"
    state: present

